### PR TITLE
Update next dependencies to ^13.0.0

### PR DESCRIPTION
**Pull request by mcamprodon**

### CODE REVIEW

**Comment by JonatanSalas** [comment]
Hi @mcamprodon! First of all thanks 🙌 for your very first time contribution to our repository! We're glad 😄 of your interest on contributing to our library ❤️.

About the PR, would love to know which motivates the following change? Because our library is fully compatible with next.js versions over or equal to version 11. 

Setting up to only over or equal version 13 would be a breaking change for our library users.

**Comment by mcamprodon** [comment]
Hi @JonatanSalas,

If I'm not mistaken the package.json file states that t[he version of next must be "^11.0.0"](https://github.com/BlackBoxVision/next-google-dfp/blob/main/package.json#L37) which indicates that only versions of next below 12.0.0 are accepted
My idea is to make the package compatible with Next 13.
How do you see it?
Thank you very much for maintaining this package, it is very useful for our projects.

**Comment by JonatanSalas** [comment]
Hi @mcamprodon! Sorry, my bad 🤦. Yes! You're right 🆗. 

For now I don't know how many sites are using our library and which versions of next they're using, bumping to support only superior to version 13 would mean a breaking change. 

Let me do some library user research to decide if we should move forward to restrict only to v13 superior versions.

You're welcome! It's really nice to see our OSS initiatives helps to boost others projects 💪.

BTW, I would ❤️ in the future to add a showcase of those that are using our library. If you're interested featuring your sites in the README that would be amazing and you can do a PR for that if you want to!

**Comment by mcamprodon** [comment]
Maybe it's better to change for ">=11.0.0"
We could also take advantage to change compatibility with react this way "react": ">=16.11.0"

If it seems good to you I can make a new PR with these modifications

**Comment by mcamprodon** [comment]
New PR created: https://github.com/BlackBoxVision/next-google-dfp/pull/5

**Comment by JonatanSalas** [comment]
@mcamprodon that's great! Thank you very much!

**Pull request closed without merging**
